ceph/ceph-csi-operator

- docs/design/operator.md
Adding intial design doc for the ceph-csi-operator
> doc: add design doc for the ceph-csi-operator

- .github/workflows/lint.yaml
config folder are auto generated and there is no need to
run codespell on auto generated files.
**Checklist:**
> ci: skip config folder from running codespell ci

- .github/workflows/build.yaml
adding CI test to run make build
For example:
**Checklist:** …
> ci: add ci test to run make build

- .github/workflows/lint.yaml
let's  clone repo with depth 1 which baiscally
fetch just gets the branch tips and no prior history.
For example:
**Checklist:** …
> ci: let's clone repo with depth 1

- Makefile
The new image varables will help exporting and replacing any of the value.
For example:
**Checklist:** …
> update image variables

- .github/workflows/lint.yaml
add `check-latest: true` in govulncheck ci to check for latest go version.
For example:
**Checklist:** …
> ci: add `check-latest: true` in govulncheck ci

- .github/workflows/lint.yaml
- config/manager/kustomization.yaml
- CRD has immediatedly keyword and linter fails. Add it into the ignore list.
- Update the image in the kustomize file.
For example:
**Checklist:**
guidelines in the …
> ignore immediatedly keyword in codespell linter and update image

- .github/workflows/lint.yaml
CRD has notin keyword and linter fails. Add it into the ignore list.
For example:
**Checklist:** …
> ignore notin keyword in codespell linter

- .golangci.yml
Discussed between repo maintainers and key contributors and agreed to opt-out of gocyclo
The PR removes gocyclo from the list of enabled linters for golangci-lint
> Diable golangci-lint gocyclo

- .github/workflows/lint.yaml
this commit exclude vendor from misspell coverage
For example:
**Checklist:** …
> ci: let's misspell from runnning on vendor folder

- .github/workflows/set_ceph_cluster.yaml
- test/scripts/collect-logs.sh
- test/scripts/github-action-helper.sh
For example:
**Checklist:**
guide](https://github.com/ceph/ceph-csi-operator/blob/devel/docs/development-gui …
> ci: add rook-ceph cluster ci test

- .golangci.yml
- test/e2e/e2e_test.go
- test/utils/utils.go
ci: add gosec in golangci lint check
adding gosec in golangci lint check, also skip gosec G204 as we don't
want to run gosec on exec method
**Checklist:**
> ci: Adding gosec in golangci lint

- .github/workflows/build.yaml
- Makefile
- config/crd/bases/csi.ceph.io_configs.yaml
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
updating github action to run git diff to check uncommitted files. The PR author sometimes forgot to push all the changes required as part of the PR. this causes inconsistency problems with the repo and local. This PR adds a check in the CI and also provides the `make` target to that developers can ensure that they are pushing all the required changes into the PR
> ci: update action to check git diff

- internal/controller/driver_controller.go
- internal/utils/csi.go
fix bugs found in nodeplugin, where the kubelet path was not specified and also the full driver name need to be present in the kubelet path for the kubelet to use cephcsi socket
> fix bugs found in controller

- internal/utils/core.go
Fix serialization cases in MapToString util
No
> Utils: fix serialization cases in MapToString util

- api/v1alpha1/clientprofilemapping_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/csi.ceph.io_clientprofilemappings.yaml
Changes BlockPoolMappings spec to list in the API
For example:
**Checklist:** …
> Use list of BlockPoolMapping in clientProfileMappings spec

- config/rbac/csi_cephfs_ctrlplugin_role_binding.yaml
- config/rbac/csi_rbd_ctrlplugin_role_binding.yaml
- config/rbac/csi_rbd_nodeplugin_role_binding.yaml
- internal/controller/driver_controller.go
- internal/utils/csi.go
1. While setting SELinuxMount on CSIDriver we need to check for existence of value set in Nodeplugin before using it or else CSIDriver will reconile infinitely due to a spurious diff
```
(dlv) p desiredCsiDriver.Spec
k8s.io/api/storage/v1.CSIDriverSpec {
AttachRequired: *true,
PodInfoOnMount: *false,
VolumeLifecycleModes: []k8s.io/api/storage/v1.VolumeLifecycleMode len: 1, cap: 1, [
"Persistent",
],
StorageCapacity: *false,
FSGroupPolicy: *"File",
TokenRequests: []k8s.io/api/storage/v1.TokenRequest len: 0, cap: 0, nil,
RequiresRepublish: *false,
SELinuxMount: *bool nil,} <=====>
(dlv) p existingCsiDriver.Spec
k8s.io/api/storage/v1.CSIDriverSpec {
AttachRequired: *true,
PodInfoOnMount: *false,
VolumeLifecycleModes: []k8s.io/api/storage/v1.VolumeLifecycleMode len: 1, cap: 1, [
"Persistent", …
```
> controllers: fix issues found in recent testing

- .github/workflows/build-push.yaml
Remove commented out quay login which is required to push the image and also remove the step to print env.
> ci: fix problem in build-push action

- internal/controller/driver_controller.go
- internal/utils/core.go
Remove empty container arguments post-creation of the arg slice.
In the future, we might want to avoid the extra step and create the original slice without the empty values
> Driver Controller: remove empty container arguments

- api/v1alpha1/driver_types.go
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
updated the validation rule for configmap name to work for all kubernetes versions.
Fixes: #92
> update validation rule for confimap name

- internal/controller/clientprofile_controller.go
- internal/controller/driver_controller.go
- internal/utils/meta.go
- internal/utils/predicates.go
If a driver CR exists but no client profile CR exists, any container that needs to mount the `ceph-csi-config` config map will fail. To solve the issue, the following behavior is added:
- Driver controller creates an empty `ceph-csi-config` config map if not already exist and adds an owner ref
- Driver controller watch for delete events for `ceph-csi-config` config map
> Driver Controller: Ensure CSI Config Creation

- api/v1alpha1/driver_types.go
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
there was cameCase type in SnapshotPolicyType enum validation.
no
For example:
Fixes: #89 #95  …
> api: fix camelCase issue SnapshotPolicyType

- internal/controller/driver_controller.go
kubernetes doesnt allow to have any special chars other than `-` in the names, we need to replace all special chars that we allow with `-` for service names.
Fixes: #88
> generate service name as per kubernetes

- config/rbac/role.yaml
- internal/controller/clientprofile_controller.go
Adds missing CephConnection delete RBAC
Delete RBAC is needed in order to enable us to add an owner reference w
no
> ClientProfile Controller: add missing CephConnection delete RBAC

- internal/controller/driver_controller.go
run csiaddons sidecar only for rbd nodeplugin its not required for cephfs/nfs and also don't run csi-addons for nfs deployment
> run csiaddons sidecar only for rbd nodeplugin

- Makefile
- config/default/kustomization.yaml
- config/manager/kustomization.yaml
- config/manager/manager.yaml
- internal/controller/defaults.go
- internal/controller/driver_controller.go
- Make commands that use kustomize no longer edit the local config folder and have zero side effects on local repo files
- Driver controller now accepts a service account prefix from an env var injected into the deployment via kustomize
- Enable setting of env vars before `build-installer`, `build-csi-rbac`, and `deploy` make target to allow kustomization. Example:
```NAME_PREFIX=\<prefix\> NAMESPACE=\<target_namspace\> make deploy``
This change also ensures that both `build-installer` and `deploy` create
RBAC, CSI RBAC, and SA accounts that allow the operator to run without
any need for manual changes!
> Configuration: Kustomisation enhancements

- config/csi-rbac/kustomization.yaml
make targets were skipping creating these files as they were not part of the kustomization resources.
For example:
**Checklist:** …
> rbac: add nfs files in the kustomization to render them

- config/default/manager_auth_proxy_patch.yaml
- config/manager/manager.yaml
This PR is adding readOnlyRootFilesystem for both containers (manager and kube-proxy) as per security standards and remove deprecated logtostderr from kube-proxy container arg
> Add readOnlyRootFilesystem and remove logtostderr

- api/v1alpha1/driver_types.go
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
- docs/design/logrotate.md
- docs/design/operator.md
- internal/controller/defaults.go
- internal/controller/driver_controller.go
- internal/utils/csi.go
1) Make main container and csi addons container
log to a file(dependency on klog)
2) Add a log-rotate sidecar container,
so it can rotate the logs
3) Added other volume and volumemounts as needed
4) Added the privileged option for controllerplugin
For example:
List …
> logrotate: add logrotate functionality for csi

- internal/controller/driver_controller.go
Fix a nil access bug when accessing DriverSpecDefaults
> Driver Controller: Fix a nil access bug when accessing DriverSpecDefaults

- api/v1alpha1/driver_types.go
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
- deploy/all-in-one/install.yaml
- deploy/multifile/crd.yaml
The omap generator is not deployed by default but the API states that it is. update the API description to the expected behaviour
Fixes: https://github.com/ceph/ceph-csi-operator/issues/131
**Checklist:**
> update api description to be inline with the expected behaviour

- Makefile
This stops `make test` from failing with a panic of  the operator by making sure OPERATOR_NAMESPACE is set in the shell environment.
It does not fix make test completely though  but lets it at least pass the first obstacle.
Do you have any questions? - no.
Is the change backward compatible? - should be.
Are there concerns around backward compatibility? - no.
Resolves: #133 
* `make test` is still failing. this should be fixed
* `make test`is not currently run in the CI. It should be.
* 
**Checklist:** …
> Makefile: fix panic in make test.

- Makefile
This follows a recommendation on a previous PR:
https://github.com/ceph/ceph-csi-operator/pull/134#discussion_r1761416232
This change  simplifies the code to  conditionally set  shell variables in the make targets `run` and `test` that was introduced in #134
No change in behavior is introduced, just a cleanup of the implementation that should make no difference to the user.
no.
should be.
no.
none
none, but see https://github.com/ceph/ceph-csi-operator/pull/134#discussion_r1761416232
no future concerns.
**Checklist:** …
> Makefile: Simplify 'test' and 'run' targets a bit.

- config/csi-rbac/cephfs_ctrlplugin_cluster_role.yaml
- config/csi-rbac/rbd_ctrlplugin_cluster_role.yaml
- deploy/all-in-one/install.yaml
- deploy/multifile/csi-rbac.yaml
Fixes 
```
W0918 10:12:09.506345       1 controller.go:989] Retrying syncing volume "pvc-1de9079b-1287-4d36-8998-db0a264b7488", failure 1                                                
E0918 10:12:09.506382       1 controller.go:1007] error syncing volume "pvc-1de9079b-1287-4d36-8998-db0a264b7488": persistentvolumes "pvc-1de9079b-1287-4d36-8998-db0a264b7488
" is forbidden: User "system:serviceaccount:openshift-storage-client:ceph-csi-rbd-ctrlplugin-sa" cannot update resource "persistentvolumes" in API group "" at the cluster sco
pe                                                                                                                                                                            
I0918 10:12:09.705796       1 controller.go:1561] delete …
```
> add missing rbac for persistentvolume during deletion

- internal/utils/csi.go
The name of the volume and the volumeMount should be the same, this commit adds the missing volumeName for the encryption mount.
No
Yes
For example:
Fixes: #146 
**Checklist:**
guidelines in the …
> add missing volume name for the encryption

- .github/workflows/lint.yaml
- .markdownlint.yaml
- docs/coding.md
- docs/development-guide.md
adding markdown lint CI check and also adding some small changes
to fix the CI
```
MD010: false # Hard tabs
MD012: false # Multiple consecutive blank lines
MD013: false # Line length
MD019: false # Multiple spaces after hash on atx style heading
MD021: false # Multiple spaces inside hashes on closed atx style heading
MD022: false # Headings should be surrounded by blank lines
MD024: false # Multiple headings with the same content
MD025: false # Multiple top-level headings in the same document
MD027: false # Multiple spaces after blockquote symbol
MD030: false # Spaces after list markers
MD031: false # Fenced code blocks should be surrounded by blank lines
MD032: false # Lists should be surrounded by blank lines
MD041: false # First line in a file should be a top-level heading
MD043: false …
```
>  ci: add markdown lint

- .github/workflows/auto-assign.yaml
- .github/workflows/dependency-review.yaml
- .github/workflows/lint.yaml
- .github/workflows/stale.yaml
- Makefile
This PR adds some github workflows to the CI as requested in #149 
* Note that for mod check, this does not only add a workflow yaml file but also a `mod.check` make 
target to be easily invoked locally by developers
* The changes are split into multiple commits: one per item. 
no questiions at this time.
It should be backward compatible.
none.
Fixes: #149 
no future concerns currently. 
**Checklist:** …
> Fix issue  149 - add some CI workflows

- internal/controller/driver_controller.go
This commit updates the condition to include the `extra-create-metadata` argument for the csi-snapshotter sidecar container when the driver type is either RBD or CephFS.
**Checklist:**
> fix: update extra-create-metadata arg condition

- internal/controller/driver_controller.go
controller-runtime accepts the pointer to the memory which is reserved by application and runtime deepcopies the object in it's cache to the memory provided by application.
this commit removes extra copy of driver spec which isn't required.
fixes: #58
> remove extra deep copy of object from cache

- docs/quick-start.md
added a quick start guide for the minimal installation
**Checklist:**
> doc: add quick-start guide

- api/v1alpha1/driver_types.go
- api/v1alpha1/zz_generated.deepcopy.go
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
- deploy/all-in-one/install.yaml
- deploy/multifile/crd.yaml
- internal/controller/defaults.go
- internal/controller/driver_controller.go
- vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/driver_types.go
- vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/zz_generated.deepcopy.go
default value is choosen in such a way to make kubernetes replace one replica when there are 2 replicas running on 2 distinct nodes.
since these replicas are already using leader election a loss of 1 replica during rollout doesn't pose any issues.
minor: fixed a typo `s/defautUpdateStrategy/defaultUpdateStrategy/`
fixes: #140
> provide ability to adjust deployment strategy

- docs/design/operator.md
I the operator design document, custom resource definition(CRD) seems to have been used as a synonym for custom resource(CR) which is usually not correct.
This change makes the wording a little clearer  by using CRD only when technically correct and using CR when appropriate.
Make some wording in the operator design doc a little clearer and more correct.
no
no
yes
no
none
none
none
**Checklist:**
Request](https://github.com/ceph/ceph-csi-operator/blob/devel/docs/development-guide.md#development-wo …
> docs: clarify the  operator design doc a bit

- .github/pull_request_template.md
Links were broken due to using a nonexistent devel branch. 
Fix this by using `main`instead. 
This fixes broken links in the PR template.
no
no
yes
no
none
Fixes: #168
none
**Checklist:**
> Fix broken links in the  PR template

- config/csi-rbac/cephfs_ctrlplugin_role.yaml
- config/csi-rbac/rbd_ctrlplugin_role.yaml
- config/csi-rbac/rbd_nodeplugin_role.yaml
- deploy/all-in-one/install.yaml
- deploy/multifile/csi-rbac.yaml
csiaddons require new RBAC permission for setting onwerRef on csiaddonsnode obj, going to be owned by either a deployment or a daemonsets. 
continued from: https://github.com/ceph/ceph-csi-operator/pull/166
No
Yes
No
RBAC's are required for this new change https://github.com/csi-addons/kubernetes-csi-addons/pull/695
For example:
will help to auto close the issue once the PR is …
> csiaddons: add rbac permission for setting ownerRef

- docs/design/hostNetwork.md
This PR adds a design document for a way to  enable  the use of host networking on Ceph-CSI controller plugin pods.
yes as it is only adding a document.
none
It is a first step toward a solution for issue #157 
but not an implementation and hence not a complete solution yet.
none. 
**Checklist:** …
> docs: add design for enforcing host network.

- .github/workflows/unit-test.yaml
- internal/controller/clientprofile_controller_test.go
- internal/controller/driver_controller_test.go
This PR fixes `make test`failures. (see issue #174 for details on the failures. 
I am not certain why current `main` branch has this issue but it was possible to get PRs with all CI check passing.  
yes.
no
This patch was created in collaboration with @raghavendra-talur .
Many thanks for the help! 
Fixes: #174 
no concerns.
**Checklist:**
notes](https://github.com/ceph/ceph-csi-operator/blob/main/PendingReleaseNotes.m …
>  fix the  Driver controller and ClientProfile controller  unit tests

- internal/controller/defaults.go
- internal/utils/csi.go
In external-snapshotter the groupsnapshot feature flag is moved to a new container argument and the old enable-volumegroup-snapshot flag is removed, This PR updates the flag to use external-snapshotter latest version,
Note:- As the flag is removed from external-snapshotter  the user cannot test/use the older version of external-snapshotter for groupsnapshot feature, but all other features will be still supported with older releases.
For example:
* golang related practices that necessitates this …
> Update externalsnapshotter volumegroupsnapshot container arg

- Makefile
- cmd/main.go
- deploy/all-in-one/install.yaml
- deploy/multifile/operator.yaml
- internal/controller/defaults.go
- internal/utils/core.go
always cache resources from operator deployed namespace and provider an option to user for caching resources from other namespaces via `WATCH_NAMESPACE` env var with a comma separated namespace values.
fixes: #184
> restrict manager resource cache based on namespaces from environment

- .github/workflows/lint.yaml
- Dockerfile
- api/go.mod
- go.mod
- test/e2e/e2e_suite_test.go
- test/utils/utils.go
- vendor/modules.txt
updating the go version to 1.23.0 as its required for kubernetes as well. 
For example:
**Checklist:** …
> ci: update go version to 1.23.0

- .github/workflows/lint.yaml
- Makefile
This PR reworks the golangci-lint make targets a bit to make them more consistent and systematic.
While at it, it makes sure the same version of golangci-lint is used locally and in the CI.
Finally, the `lint` CI workflow is changed to use the golangci-lint make target instead of the corresponding github action. 
yes.
no.
none 
**Checklist:**
notes](https://github.com/ceph/ceph-csi-operator/blob/main/PendingReleaseNotes.md)
updated with breaking and/or notable changes …
> Rework golangci lint

- config/csi-rbac/cephfs_ctrlplugin_role.yaml
- config/csi-rbac/rbd_ctrlplugin_role.yaml
- config/csi-rbac/rbd_nodeplugin_role.yaml
- deploy/all-in-one/install.yaml
- deploy/multifile/csi-rbac.yaml
Introduce changes to support CSI addons security changes introduced in https://github.com/csi-addons/kubernetes-csi-addons/pull/692
**Checklist:**
notes](https://github.com/ceph/ceph-csi-operator/blob/main/PendingReleaseNotes.md)
> Add TokenReview RBAC to support CSI addons security enhancements

- internal/controller/driver_controller.go
- internal/utils/csi.go
Previously, the function incorrectly checked if `len(options) == 0`, causing it to return a non-empty argument when no options were provided. This fix updates the condition to `len(options) > 0`, ensuring the argument is only set when options exist.
**Checklist:**
> csi: correct conditional logic for fuse mount options argument

- internal/controller/driver_controller.go
- internal/utils/csi.go
This file provides functionality to store various mount information in a file. It's currently used to restore ceph-fuse mounts. Mount info is stored in `/csi/mountinfo`.
**Checklist:**
> csi: add missing mount-info volumeMount for cephfs

- internal/controller/defaults.go
The csi-addons v0.12.0 release is now available.
See-also: https://github.com/csi-addons/kubernetes-csi-addons/releases/tag/v0.12.0
> Update the csi-addons sidecar to v0.12.0

- config/csi-rbac/cephfs_ctrlplugin_cluster_role.yaml
- config/csi-rbac/cephfs_ctrlplugin_role.yaml
- config/csi-rbac/rbd_ctrlplugin_cluster_role.yaml
- config/csi-rbac/rbd_ctrlplugin_role.yaml
- config/csi-rbac/rbd_nodeplugin_cluster_role.yaml
- config/csi-rbac/rbd_nodeplugin_role.yaml
- deploy/all-in-one/install.yaml
- deploy/charts/ceph-csi-operator/templates/cephfs-ctrlplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-operator/templates/cephfs-ctrlplugin-r-rbac.yaml
- deploy/charts/ceph-csi-operator/templates/rbd-ctrlplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-operator/templates/rbd-ctrlplugin-r-rbac.yaml
- deploy/charts/ceph-csi-operator/templates/rbd-nodeplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-operator/templates/rbd-nodeplugin-r-rbac.yaml
- deploy/multifile/csi-rbac.yaml
Updates RBAC configuration to support CSI addons security changes introduced in https://github.com/csi-addons/kubernetes-csi-addons/pull/692
TokenReview permission needs to be applied to ClusterRole previously it was applied to Role
**Checklist:**
notes](https://github.com/ceph/ceph-csi-operator/blob/main/PendingReleaseNotes.md)
> Fix RBAC permissions for CSI addons security enhancements

- vendor/github.com/ceph/ceph-csi-operator/api/v1alpha1/driver_types.go
pushed missed vendor changes as CI was down when PR was created.
> fix: push missed vendor changes

- .github/workflows/test-chart.yml
- deploy/charts/ceph-csi-drivers/.helmignore
- deploy/charts/ceph-csi-drivers/Chart.yaml
- deploy/charts/ceph-csi-drivers/templates/_helpers.tpl
- deploy/charts/ceph-csi-drivers/templates/cephConnection.yaml
- deploy/charts/ceph-csi-drivers/templates/cephfs-ctrlplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/cephfs-ctrlplugin-crb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/cephfs-ctrlplugin-r-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/cephfs-ctrlplugin-rb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/cephfs-nodeplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/cephfs-nodeplugin-crb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/clientProfiles.yaml
- deploy/charts/ceph-csi-drivers/templates/driver.yaml
- deploy/charts/ceph-csi-drivers/templates/nfs-ctrlplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/nfs-ctrlplugin-crb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/nfs-nodeplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/nfs-nodeplugin-crb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/operatorConfig.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-ctrlplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-ctrlplugin-crb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-ctrlplugin-r-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-ctrlplugin-rb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-nodeplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-nodeplugin-crb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-nodeplugin-r-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/rbd-nodeplugin-rb-rbac.yaml
- deploy/charts/ceph-csi-drivers/templates/serviceaccount.yaml
- deploy/charts/ceph-csi-drivers/values.yaml
Adding a helm chart to create all the required CR's to have successful 3 csi drivers(cephfs/rbd/nfs)
> chart: Add helm charts for ceph-csi drivers

- internal/controller/driver_controller.go
Setting SELinuxMount in the csi driver spec to true by default like we have it in Rook.
The Field we have it in the Driver spec EnableSeLinuxHostMount is to mount the below path to the csi driver daemonset as the Field description specifies.
https://github.com/ceph/ceph-csi-operator/blob/ae5677274f13fabf0aea26fbfbe2157817ed6046/api/v1alpha1/driver_types.go#L175-L177
```
-  name: etc-selinux
mountPath: /etc/selinux
readOnly: true
```
> fix: set SELinuxMount to true

- go.mod
- go.sum
- vendor/golang.org/x/oauth2/README.md
- vendor/golang.org/x/oauth2/oauth2.go
- vendor/golang.org/x/oauth2/pkce.go
- vendor/modules.txt
updating oauth to fix the mentioned CVE CVE-2025-22868.
> fix: update oauth to fix CVE-2025-22868

- .github/workflows/lint.yaml
- test/scripts/test-ceph-csi-operator.sh
Its not possible to get the third party github action to be used automatically in the ceph org, All the actions need to be audited, The currently used one are having problems, Replacing it with our own until we find a fix for using third party actions again.
> ci: install the tools required for linting

- internal/controller/driver_controller.go
- internal/utils/csi.go
If the admin sets the domain label in the nodeplugin we need to set the topology featuregate to true
in the controller deployment as the feature needs to be enabled on the both provisioner and the nodeplugin , If the domain labels are not set we need to disable the toplogy as its enabled by default.
> fix: set topology flag if csi driver advertize it

- .github/workflows/publish-helm-charts.yaml
Push the operator and the csi driver helm charts to the gh-pages when there is a new release of the operator.
This is replacement PR for https://github.com/ceph/ceph-csi-operator/pull/233
> ci: add github action for helm charts

- .github/workflows/test-chart.yml
- internal/controller/defaults.go
This PR includes below changes
* Use local built operator image for testing
* Use the available resizer and the node-registrar for testing (the new image still takes time to get push from kubernetes-csi )
> Fix: Use available images for testing

- .github/workflows/publish-helm-charts.yaml
we are pushing the chart tag.gz file to the gh-pages repo, we dont need to add it to the release. removing the extra step and also added step to push the chart to the release itself
depends-in: #257
> ci: remove uploading step to the release

- .github/workflows/publish-helm-charts.yaml
For now we are only setting the version in the helm chart to install the specific version of it, There is another field in the
helm chart that represents the app version. Setting the appVersion similar to version to avoid confusion.
> helm: set appVersion in the helm charts

- .github/workflows/test-charts.yaml
- .github/workflows/test_operator.yaml
if there is any change in the documentation or some config files that doesnt impact the operator or the csi driver, we dont run the github actions that will test the operator and the csi driver.
> ci: skip running operator tests

- internal/controller/driver_controller.go
Fix method name typo from `isRdbDriver()` to `isRbdDriver()`.
**Checklist:**
> fix: correct typo RdbDriver to isRbdDriver

- PendingReleaseNotes.md
- config/csi-rbac/cephfs_nodeplugin_cluster_role.yaml
- config/csi-rbac/cephfs_nodeplugin_role.yaml
- config/csi-rbac/cephfs_nodeplugin_role_binding.yaml
- config/csi-rbac/rbd_nodeplugin_cluster_role.yaml
- deploy/all-in-one/install.yaml
- deploy/charts/ceph-csi-operator/templates/cephfs-nodeplugin-cr-rbac.yaml
- deploy/charts/ceph-csi-operator/templates/rbd-nodeplugin-cr-rbac.yaml
- deploy/multifile/csi-rbac.yaml
- internal/controller/driver_controller.go
- internal/utils/csi.go
When a Driver gets annotated with
addons.csi.ceph.io/volume-condition: true
the CSI-Addons DaemonSet for that driver will get deployed with the extra `--enable-volume-condition=true` commandline flag. This causes the CSI-Addons sidecar to periodically check attached volumes for this Driver and report the condition in the logs of the sidecar and as an Event for the PersistentVolumeClaim.
The volume condition reporter has been merged in csi-addons/kubernetes-csi-addons#831, but a release is still pending. That means the `--enable-volume-condition` commandline flag for the sidecar does not work without replacing the container-image with `quay.io/csiaddons/k8s-sidecar:latest`.
- currently CSI-Addons for NFS is forcefully disabled, this should become optional too
**Checklist:**
guidelines in …
> Deploy CSI-Addons with volume condition reporter

- api/v1/driver_types.go
- api/v1/zz_generated.deepcopy.go
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
- deploy/all-in-one/install.yaml
- deploy/charts/ceph-csi-operator/templates/driver-crd.yaml
- deploy/charts/ceph-csi-operator/templates/operatorconfig-crd.yaml
- deploy/multifile/crd.yaml
- internal/controller/driver_controller.go
- internal/utils/csi.go
- vendor/github.com/ceph/ceph-csi-operator/api/v1/driver_types.go
- vendor/github.com/ceph/ceph-csi-operator/api/v1/zz_generated.deepcopy.go
Ceph-CSI added `enable-fencing` flag in https://github.com/ceph/ceph-csi/pull/5429/commits/e77ce041a9ab5c9fa8903acbbfed0ae9a50a7e04
```
Introduce a new flag 'enable-fencing' false by default.
When enabled driver can set the client address per node in
the volume metadata during NodeStageVolume operation and
fence the node in ControllerUnpublishVolume and unfence
the node in ControllerPublishVolume using the address stored
in the volume metadata.
```
This PR adds the support for the same.
Ref:
- https://github.com/ceph/ceph-csi/pull/5429
**Checklist:**
> api: add enable fencing flag

- docs/design/hostNetwork.md
- docs/design/logrotate.md
- docs/design/operator.md
- docs/kubernetes-installation.md
- docs/quick-start.md
The API moved to v1, but the quickstart and other documents still
referred to v1alpha1.
> doc: use csi.ceph.io/v1 instead of v1alpha1

- internal/controller/defaults.go
Kubernetes CSI-Addons 0.13.0 has been released today: https://github.com/csi-addons/kubernetes-csi-addons/releases/tag/v0.13.0 This release contains the Volume Condition Reporter that can be enabled by annotating the driver CR.
See-also: #282
> update Kubernetes CSI-Addons sidecar to v0.13.0

- internal/controller/driver_controller.go
```
This commit adds a check for snapshotmetadataservice crd existence
before checking if the CR exists. This is done to avoid unwanted
error logs when the CRD is not present in the cluster.
```
Fixes: #297 
**Checklist:**
> csi: add snapshotmetadataservice crd existence check

- internal/controller/defaults.go
This patch changes the default update strategy for controller plugin to Recreate from RollingUpdate.
This helps fix the situation where we end up in a scheduling deadlock due to affinity and anti affinity rules.
Fixes: #312, #273
> driver: Change controller-plugin deployment strategy to Recreate

- Makefile
- deploy/charts/ceph-csi-drivers/templates/serviceaccount.yaml
- deploy/charts/ceph-csi-drivers/values.yaml
- deploy/charts/ceph-csi-operator/templates/deployment.yaml
- deploy/charts/ceph-csi-operator/templates/serviceaccount.yaml
- deploy/charts/ceph-csi-operator/values.yaml
- docs/helm-charts/drivers-chart.md
- docs/helm-charts/operator-chart.md
- hack/patch-sa-with-imgpullsecrets.sh
This patch adds option to specify `imagePullSecrets` for operator deployments.
A new `patch-sa-with-imgpullsecrets` script is also added as a post step of `build-helm-installer`
to inject the pull secrets into operator's serviceaccount.
_macOS requires GNU AWK (gawk) installed in order for variable expansion to work properly._
Closes: #305
> Allow user to specify `imagePullSecrets` for csi-operator deployments

- api/v1/driver_types.go
- config/crd/bases/csi.ceph.io_drivers.yaml
- config/crd/bases/csi.ceph.io_operatorconfigs.yaml
- deploy/all-in-one/install.yaml
- deploy/charts/ceph-csi-operator/templates/driver-crd.yaml
- deploy/charts/ceph-csi-operator/templates/operatorconfig-crd.yaml
- deploy/multifile/crd.yaml
- vendor/github.com/ceph/ceph-csi-operator/api/v1/driver_types.go
This patch updates the documentation for controller plugin deployment strategy.
It was changed to `Recreate` from `RollingUpdate` with #322
> api: Update documentation for deployment strategy
