.github/workflows/lint.yaml

this commit add github action linters like
golangci, codespell, markdownlint, misspell, govulncheck.

ci: add github action linters

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/dependabot.yml
.github/pull_request_template.md

Adding templates required for pull request and issues and also added a template for dependabot

Add template for the .github 

---

LICENSE
PendingReleaseNotes.md
docs/DCO
docs/coding.md
docs/development-guide.md
docs/releases.md

Adding more documentations for the process
to follow.

doc: adding more documentation for process

---

api/v1alpha1/driver_types.go
internal/controller/driver_controller.go

The existing code ignores the driver's SnapshotPolicy settings. This PR fix the behavior.
No

Driver Controller: Fix support for SnapshotPolicy settings

---

config/rbac/kustomization.yaml

Add CSI operand RBAC kustomization file
Operands SA and RBAC will now be included in the product of "make build-installer"
No

Configuration: Add CSI operand RBAC kustomization file

---

.github/workflows/lint.yaml
.github/workflows/test_operator.yaml
.gitignore
test/scripts/test-ceph-csi-operator.sh
test/scripts/utils.sh

This updates the CI job to build and deploy the cephcsi operator and check if it's running or not.

Update ci test

---

api/v1alpha1/clientprofile_types.go
api/v1alpha1/driver_types.go
config/crd/bases/csi.ceph.io_clientprofiles.yaml
config/crd/bases/csi.ceph.io_drivers.yaml
config/crd/bases/csi.ceph.io_operatorconfigs.yaml

Add CEL validations for:
- `<driver>.metadata.name` must match "(<prefix>.)[rbd|cephfs|nfs].csi.ceph.com"
- `<driver>.spec.imageSet.name` cannot be empty
- `<driver>.sepc.encryption.configMapRef.name` cannot be empty
- `<clientprofile>.spec.cephConnectionRef.name` cannot be empty

APIs: Additional validations

---

api/v1alpha1/driver_types.go
config/crd/bases/csi.ceph.io_drivers.yaml
config/crd/bases/csi.ceph.io_operatorconfigs.yaml

add a missing `,` inside the json tag or else it is considered inside as a new field in the spec.

fix inline in json

---

.github/workflows/build-push.yaml
.gitignore

This PR adds a GitHub action to build and push multi-arch docker images to quay.io

ci: github action for docker build push

---

internal/controller/driver_controller.go

improve logging to log both actual and expected details which helps for debugging.
fixes: #53

impore logging for invalid driver name

---

internal/controller/driver_controller.go

Fix nil ref access and remove unnecessary mem copy

Driver Controller: Fix nil ref access and remove unnecessary mem copy

---

config/csi-rbac/cephfs_ctrlplugin_role.yaml

Configuration: Add missing CSI RBAC

---

internal/controller/driver_controller.go

Fix GRpcTimeout issues for resizer container
no

Driver Controller: Fix GRpcTimeout issues for resizer container

---

docs/design/logrotate.md

updating the logrotation design doc for the CRD changes we have done in the repo.

doc: update logrotation design doc

---

internal/controller/driver_controller.go

Multi-layer image set loading logic:
- start with hardcoded default
- overwrite any image specified in a config map referred to by the operator config driver default spec. CM is expected to resign in the operator namespace
- overwrite any image specified in a config map referred to by the driver spec. CM is expected to resign in the driver namespace

Driver Controller: Multi-layer image set loading logic

---

README.md

updating the readme contents for this repo and note that there are pointers to some files like installation and usage which don't exist yet but we plan to add those soon.
Yes
For example:
Fixes: #51
**Checklist:**
guidelines in …

doc: update readme contents

---

.github/workflows/test_operator.yaml
test/scripts/github-action-helper.sh

update the required packages for the kubernetes installation.

ci: update dependencies for kubernetes

---

internal/controller/defaults.go

this commit updates the cephcsi verison to
v3.13.1

Update the cephcsi version to v3.13.1

---

internal/controller/clientprofilemapping_controller_test.go

addressing golangci-lint error.

fix: address golangci-lint error

---

internal/controller/driver_controller.go

csi: fix missing additional volumeMounts to nodeplugin container
**Checklist:**

csi: fix missing additional volumeMounts in nodeplugin container

---

internal/controller/driver_controller.go

fix: merge EnableFencing from driverSpecDefaults to driverSpec

fix: merge EnableFencing from driverSpecDefaults to driverSpec

---

internal/controller/defaults.go

We have new release for Ceph-CSI v3.15.0 -
https://github.com/ceph/ceph-csi/releases/tag/v3.15.0
**Checklist:**

csi: update ceph-csi to v3.15.0

---

Makefile
deploy/all-in-one/install.yaml
deploy/charts/ceph-csi-operator/values.yaml
deploy/multifile/operator.yaml
docs/helm-charts/operator-chart.md

Updating the image tag in makefile and in templates for 0.4.1 release.

ci: update templates for 0.4.1 release
